"use client";

import { useEffect } from "react";
import { useDispatch } from "react-redux";
import { useRouter } from "next/navigation";

import { confirmLogin, logoutAction } from "@/store/auth-actions";

export const metadata = {
  title: "First Project | Dashboard",
  description: "Generated by Next.js",
};

export default function DashboardLayout({ children }) {
  const router = useRouter();
  const dispatch = useDispatch();

  useEffect(() => {
    const userDetails = localStorage.getItem("userDetails");

    if (!userDetails) {
      router.replace("/login");
      return;
    }

    const userDetailsValues = JSON.parse(userDetails);

    dispatch(confirmLogin(userDetailsValues));
  }, [dispatch]);

  const logoutHandler = () => {
    dispatch(logoutAction());
    router.replace("/login");
  };

  return (
    <main>
      <nav>
        <h2>User Dashboard</h2>
        <button onClick={logoutHandler}>Logout</button>
      </nav>
      {children}
    </main>
  );
}
