import MainNavigation from "./components/Header/MainNavigation";

export const metadata = {
  title: "First Project",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <MainNavigation />
        {children}
      </body>
    </html>
  );
}
