export const metadata = {
  title: "First Project | About",
  description: "Generated by Next.js",
};

const AboutPage = () => {
  return (
    <div>
      <h1>This is my aboutage</h1>
    </div>
  );
};

export default AboutPage;
